declare global {
  type HTMLCardElement = HTMLDivElement;
  type HTMLTopCardElement = HTMLDivElement;

  const loadingScreen: HTMLDivElement;
  const lightLoadingSpinner: HTMLImageElement;
  const darkLoadingSpinner: HTMLImageElement;
  const loadingText: HTMLHeadingElement;
  const homepage: HTMLDivElement;
  const mainCardsContainer: HTMLDivElement;
  const tabs: HTMLDivElement;
  const discordTabButton: HTMLButtonElement;
  const blogTabButton: HTMLButtonElement;
  // const steambutton: HTMLButtonElement;
  const settingsTabButton: HTMLButtonElement;
  const mainCard: HTMLCardElement;
  const discordPath: HTMLDivElement;
  const pfp: HTMLImageElement;
  const username: HTMLDivElement;
  const customStatus: HTMLDivElement;
  const onlineState: HTMLDivElement;
  const platforms: HTMLDivElement;
  const blogCard: HTMLCardElement;
  const activityCard: HTMLCardElement;
  const activityPath: HTMLDivElement;
  const aboutCard: HTMLCardElement;
  const aboutPath: HTMLDivElement;
  const abm1: HTMLLIElement;
  const abm2: HTMLLIElement;
  const linksCard: HTMLCardElement;
  const stuffPath: HTMLDivElement;
  const mainbtn3: HTMLButtonElement;
  const mainbtn1: HTMLButtonElement;
  const mainbtn2: HTMLButtonElement;
  const settings: HTMLDivElement;
  const settingsclose: HTMLTopCardElement;
  const backbtn: HTMLDivElement;
  const settingsDoNotHide: HTMLCardElement;
  const settingsPath: HTMLDivElement;
  const languagetxt: HTMLHeadingElement;
  const language2: HTMLSelectElement;
  const selopt: HTMLOptionElement;
  const themetxt: HTMLHeadingElement;
  const themeOption: HTMLSelectElement;
  const selopt2: HTMLOptionElement;
  const darkthmopt: HTMLOptionElement;
  const lightthmopt: HTMLOptionElement;
  const saveBtn: HTMLButtonElement;
  const lastUpdated: HTMLParagraphElement;
}

export {};